name: dopa
description: Dopa mobile application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.13.0 <3.14.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  path_provider: ^2.1.5
  dopa_domain:
    path: ../../packages/domain
  dopa_local_storage:
    path: ../../packages/local_storage
  drift_flutter: ^0.3.1

dev_dependencies:
  drift: ^2.34.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tree/
