include: ../../analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
